In [5]:
from gaussElimin import *
import numpy as np

In [6]:
A=np.array([[3,-1,2],[1,1,2],[2,-2,-1]])
b = np.array([[7],[9],[-5]])
print(A)
print(b)

[[ 3 -1  2]
 [ 1  1  2]
 [ 2 -2 -1]]
[[ 7]
 [ 9]
 [-5]]


In [7]:
ans = gaussElimin(A,b)
print(ans)

[[1]
 [3]
 [3]]
