In [1]:
from LUdecomp import *

In [1]:
A = [[4,12,8,4],[1,7,18,9],[2,9,20,20],[3,11,15,14]]

In [5]:
a = LUdecomp(np.array(A))
print(a)

[[ 4 12  8  4]
 [ 0  4 16  8]
 [ 0  0  4 12]
 [ 0  0  0  4]]


In [2]:
from LUdecompx import *
from ppmat import *

In [3]:
A = [[4,12,8,4],[1,7,18,9],[2,9,20,20],[3,11,15,14]]
a,L = LUdecompx(np.array(A))
print(a)
ppmat(L)

[[ 4 12  8  4]
 [ 1  4 16  8]
 [ 2  9 20 20]
 [ 3 11 15 14]]
[[ 4 12  8  4]
 [ 0  4 16  8]
 [ 2  3 16 18]
 [ 3 11 15 14]]
[[ 4 12  8  4]
 [ 0  4 16  8]
 [ 0  3 16 18]
 [ 3  2  9 11]]
[[ 4 12  8  4]
 [ 0  4 16  8]
 [ 0  3  4 12]
 [ 0  2  9 11]]
[[ 4 12  8  4]
 [ 0  4 16  8]
 [ 0  0  4 12]
 [ 0  2  1  7]]
[[ 4 12  8  4]
 [ 0  4 16  8]
 [ 0  0  4 12]
 [ 0  0  1  4]]
[[ 4 12  8  4]
 [ 0  4 16  8]
 [ 0  0  4 12]
 [ 0  0  0  4]]

    1   ,     0   ,     0   ,     0   
  1/4   ,     1   ,     0   ,     0   
  1/2   ,   3/4   ,     1   ,     0   
  3/4   ,   1/2   ,   1/4   ,     1   


In [4]:
import numpy as np
L = np.array(L)
U = np.array(a)
c = L.dot(U)
ppmat(L)
print("--------------------------")
print(U)
print("==========================")
ppmat(c)


    1   ,     0   ,     0   ,     0   
  1/4   ,     1   ,     0   ,     0   
  1/2   ,   3/4   ,     1   ,     0   
  3/4   ,   1/2   ,   1/4   ,     1   
--------------------------
[[ 4 12  8  4]
 [ 0  4 16  8]
 [ 0  0  4 12]
 [ 0  0  0  4]]

    4   ,    12   ,     8   ,     4   
    1   ,     7   ,    18   ,     9   
    2   ,     9   ,    20   ,    20   
    3   ,    11   ,    15   ,    14   
