In [1]:
from LUdecomp3 import *
import numpy as np

In [2]:
c = np.array([4,1,2,5,0])
d = np.array([1,17,3,1,21])
e = np.array([0,4,2,0,4])
A = np.array([[1,4,0,0,0],[4,17,1,0,0],[0,2,3,2,0],[0,0,0,1,5],[0,0,0,4,21]])
r = np.array([[-7],[-27],[-3],[21],[89]])

In [3]:
B,D,E = LUdecomp3(c,d,e)
print(B)
print("============")
print(D)
print("============")
print(E)

[ 4  0  1 -5  0]
[ 1 17  2 -1 21]
[0 4 2 0 4]


In [4]:
x = LUsolve3(B,D,E,r)
print(x)

[[ -7]
 [ -5]
 [ 22]
 [-24]
 [  9]]


In [5]:
from LUdecomp import *

In [6]:
a = LUdecomp(A)

In [7]:
print(a)

[[1 4 0 0 0]
 [4 1 1 0 0]
 [0 2 1 2 0]
 [0 0 0 1 5]
 [0 0 0 4 1]]


In [8]:
x = LUsolve(a,r)
print(x)

[[ 4197]
 [-1051]
 [ 1074]
 [ -549]
 [  105]]
