In [28]:
from LU_Solve import *
import numpy as np

In [29]:
A = np.array([[2,6,10],[1,3,3],[3,14,28]])
b = np.array([[0],[2],[-8]])

In [30]:
from scipy.linalg import lu_factor, lu_solve
from numpy import tril, triu, allclose, zeros, eye

In [31]:
lu, piv = lu_factor(A)
print('lu:')
print(lu)
print('********************************************')
print('piv:')
print(piv)
x = lu_solve((lu, piv), b)
print(x)

lu:
[[ 3.         14.         28.        ]
 [ 0.66666667 -3.33333333 -8.66666667]
 [ 0.33333333  0.5        -2.        ]]
********************************************
piv:
[2 2 2]
[[ 2.]
 [ 1.]
 [-1.]]


In [32]:
import scipy.linalg as ALG
P,L,U= ALG.lu(A,permute_l = False)
print('P:')
print(P)
print('************************************************')
print('L:')
print(L)
print('************************************************')
print('U:')
print(U)

P:
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
************************************************
L:
[[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.5        1.        ]]
************************************************
U:
[[ 3.         14.         28.        ]
 [ 0.         -3.33333333 -8.66666667]
 [ 0.          0.         -2.        ]]


In [36]:
P = np.array([[0,0,1],[1,0,0],[0,1,0]])
c = P @ b
print(c.T)
# 解 Ly = c
y = np.linalg.solve(L,c)
print(y.T)
# 解 Ux = y
x = np.linalg.solve(U,y)
print(x.T)

[[-8  0  2]]
[[-8.          5.33333333  2.        ]]
[[ 2.  1. -1.]]


### example from: https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu_factor.html

In [11]:
A1 = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
lu1, piv1 = lu_factor(A1,permute_l == False)

In [12]:
print(lu1,piv1)

[[ 7.          5.          6.          6.        ]
 [ 0.28571429  3.57142857  6.28571429  5.28571429]
 [ 0.71428571  0.12       -1.04        3.08      ]
 [ 0.71428571 -0.44       -0.46153846  7.46153846]] [2 2 3 3]


In [13]:
piv_py = [2, 0, 3, 1]
L1, U1 = np.tril(lu1, k=-1) + np.eye(4), np.triu(lu1)

In [15]:
np.allclose(A1[piv_py] - L1 @ U1, np.zeros((4, 4)))

True