In [1]:
from power_B import *
from rayleigh import *
from Aitken import *
import numpy as np

In [2]:
A = np.array([[40.5,10.5,-21.0,21.0],[10.5, 20.5, -5.0, 5.0],[-21.0, -5.0, 37.0, -1.0],[21.0, 5.0, -1.0, 37.0]])
z = [[1.0],[1.0],[1.0],[1.0]]
print(A)

[[ 40.5  10.5 -21.   21. ]
 [ 10.5  20.5  -5.    5. ]
 [-21.   -5.   37.   -1. ]
 [ 21.    5.   -1.   37. ]]


In [3]:
np.set_printoptions(precision=5)
[eigs,vecs] = power_B(A,z,16,0.0001)
print('eigs: ',eigs)
for x in vecs.T:
    print(x,end='')
print()

iter       w1    r  z(x)
1 [62.] 27.090638706296474 [[0.8226 0.5    0.1613 1.    ]]
2 [56.6129] 24.217358194211986 [[ 0.9923  0.4077 -0.2615  1.    ]]
3 [70.9615] 9.450017377335088 [[ 1.      0.3535 -0.4728  0.8475]]
4 [71.9385] 4.774350399891018 [[ 1.      0.3385 -0.5715  0.7589]]
5 [71.9923] 2.3871292808706555 [[ 1.      0.3346 -0.6194  0.7132]]
6 [71.999] 1.1933549903494673 [[ 1.      0.3337 -0.6431  0.69  ]]
7 [71.9999] 0.5966374446612831 [[ 1.      0.3334 -0.6549  0.6784]]
8 [72.] 0.2983128166467088 [[ 1.      0.3334 -0.6608  0.6725]]
9 [72.] 0.14915561283678708 [[ 1.      0.3333 -0.6637  0.6696]]
10 [72.] 0.07457770336948963 [[ 1.      0.3333 -0.6652  0.6681]]
11 [72.] 0.03728883857678053 [[ 1.      0.3333 -0.6659  0.6674]]
12 [72.] 0.018644417635679984 [[ 1.      0.3333 -0.6663  0.667 ]]
13 [72.] 0.009322208610358844 [[ 1.      0.3333 -0.6665  0.6668]]
14 [72.] 0.0046611042791937524 [[ 1.      0.3333 -0.6666  0.6668]]
15 [72.] 0.0023305521363436443 [[ 1.      0.3333 -0.6666  0.6

#### 將矩陣H平移20  (H = A - 20*I)

In [4]:
H = A - 20 * np.eye(4)
print(H)

[[ 20.5  10.5 -21.   21. ]
 [ 10.5   0.5  -5.    5. ]
 [-21.   -5.   17.   -1. ]
 [ 21.    5.   -1.   17. ]]


In [5]:
[eigs,vecs] = power_B(H,z,15,0.0001)
print('eigs: ',eigs)
for x in vecs.T:
    print(x,end='')
print()

iter       w1    r  z(x)
1 [42.] 19.472668211014014 [[ 0.7381  0.2619 -0.2381  1.    ]]
2 [43.881] 12.610360253087753 [[ 1.      0.3207 -0.4981  0.7759]]
3 [50.6213] 2.9377925849508633 [[ 1.      0.3364 -0.6291  0.7169]]
4 [52.2996] 0.8140018593847306 [[ 1.      0.3327 -0.6519  0.6788]]
5 [51.937] 0.22917912057134915 [[ 1.      0.3335 -0.6628  0.6711]]
6 [52.0133] 0.06763551622574539 [[ 1.      0.3333 -0.6653  0.6679]]
7 [51.9972] 0.020351774327402466 [[ 1.      0.3333 -0.6663  0.6671]]
8 [52.0006] 0.006195885204303088 [[ 1.      0.3333 -0.6665  0.6668]]
9 [51.9999] 0.0018966134558153968 [[ 1.      0.3333 -0.6666  0.6667]]
10 [52.] 0.0005821478839237227 [[ 1.      0.3333 -0.6667  0.6667]]
11 [52.] 0.00017891428102810255 [[ 1.      0.3333 -0.6667  0.6667]]
12 [52.] 5.5020280786897434e-05 [[ 1.      0.3333 -0.6667  0.6667]]
Power Method has coverged
eigs:  [52.]
[ 1.      0.3333 -0.6667  0.6667]


In [6]:
[eigs,vecs] = rayleigh(H,z,15,0.0001)
print('eigs: ',eigs)
for x in vecs.T:
    print(x,end='')
print()

iter     m       r     z(x)
1     [18.5] 19.85 [[0.5 0.5 0.5 0.5]]
2     [45.1032] 14.74 [[ 0.5711  0.2027 -0.1842  0.7738]]
3     [51.2577] 5.197 [[ 0.7156  0.2295 -0.3564  0.5552]]
4     [51.93] 1.597 [[ 0.7031  0.2365 -0.4423  0.5041]]
5     [51.9934] 0.488 [[ 0.7078  0.2354 -0.4614  0.4804]]
6     [51.9994] 0.149 [[ 0.707   0.2358 -0.4686  0.4744]]
7     [51.9999] 0.045 [[ 0.7071  0.2357 -0.4705  0.4723]]
8     [52.] 0.014 [[ 0.7071  0.2357 -0.4711  0.4717]]
9     [52.] 0.004 [[ 0.7071  0.2357 -0.4713  0.4715]]
10    [52.] 0.001 [[ 0.7071  0.2357 -0.4714  0.4714]]
11    [52.] 0.000 [[ 0.7071  0.2357 -0.4714  0.4714]]
12    [52.] 0.000 [[ 0.7071  0.2357 -0.4714  0.4714]]
13    [52.] 3.888 [[ 0.7071  0.2357 -0.4714  0.4714]]
Power Method has coverged
eigs:  [52.]
[ 0.7071  0.2357 -0.4714  0.4714]


In [9]:
[eigs,vecs,Ait] = Aitken(H,z,15,0.0001)

for x in vecs.T:
    print(x,end='')
print()
print('Power_RQ:')
for t in eigs:
    print('%8.4f'% t,', ',end='')
    if t==5 :
        print()
print()
print('Aitken:')
for y in Ait:
    print('%8.4f'% y,', ',end='')
    if y==5:
        print()
print()

iter     m       r     z(x)
1     18.5 19.85 [[0.5 0.5 0.5 0.5]]
2     18.5 14.74 [[ 0.5711  0.2027 -0.1842  0.7738]]
3     18.5 5.197 [[ 0.7156  0.2295 -0.3564  0.5552]]
4     18.5 1.597 [[ 0.7031  0.2365 -0.4423  0.5041]]
5     18.5 0.488 [[ 0.7078  0.2354 -0.4614  0.4804]]
6     18.5 0.149 [[ 0.707   0.2358 -0.4686  0.4744]]
7     18.5 0.045 [[ 0.7071  0.2357 -0.4705  0.4723]]
8     18.5 0.014 [[ 0.7071  0.2357 -0.4711  0.4717]]
9     18.5 0.004 [[ 0.7071  0.2357 -0.4713  0.4715]]
10    18.5 0.001 [[ 0.7071  0.2357 -0.4714  0.4714]]
11    18.5 0.000 [[ 0.7071  0.2357 -0.4714  0.4714]]
12    18.5 0.000 [[ 0.7071  0.2357 -0.4714  0.4714]]
13    18.5 3.888 [[ 0.7071  0.2357 -0.4714  0.4714]]
Power Method has coverged
[ 0.7071  0.2357 -0.4714  0.4714]
Power_RQ:
 18.5000 ,  45.1032 ,  51.2577 ,  51.9300 ,  51.9934 ,  51.9994 ,  51.9999 ,  52.0000 ,  52.0000 ,  52.0000 ,  52.0000 ,  52.0000 ,  52.0000 ,   0.0000 ,   0.0000 , 
Aitken:
  0.0000 ,   0.0000 ,   0.0000 ,  52.0124 ,  52.0000 , 