In [1]:
from Inv_Power import *
from numpy import *
import scipy.linalg as ALG

In [2]:
# A 的特徵值中最靠近 b=15 的值
A = np.array([[21,7,-1],[5,7,7],[4,-4,20]])
m, mm = inv_power(A,4,0.0001 )
print('m:')
for i in range(len(m)):
    print('%8.4f'%m[i],end='')
print()
print('=================================')
print('mm = 1/m = ',end='')
print('%8.5f'%mm)

iter     m      r      z(n)
1     0.0503   0.0157  0.5774  0.5774  0.5774
2     0.0694   0.0269  0.3136  0.7128  0.6273
3     0.0984   0.0244 -0.0399  0.8060  0.5905
4     0.1148   0.0124 -0.2674  0.8185  0.5085
m:
 -0.2674  0.8185  0.5085
mm = 1/m =  8.70720


In [3]:
# 平移
B = A - 15*np.eye(len(A))
print(B)

[[ 6.  7. -1.]
 [ 5. -8.  7.]
 [ 4. -4.  5.]]


In [6]:
# step 1
# 求解 Bw = z, 由 z = [1,1,1]' 開始
z = np.array([[1],[1],[1]])
w = np.linalg.solve(B,z)
print(w.T)

[[0.03174603 0.15873016 0.3015873 ]]


In [7]:
# 取絕對值最大之特徵值
newW = max(abs(w))   # also w(k)/z(k)
print(newW)

[0.3015873]


In [14]:
ndx = list(w).index(newW)
#1/m = z[ndx]/w[ndx]
m = 1/newW
print('%8.4f'%(m))

  3.3158


In [16]:
# 步驟二
##將 w 尺度化
z = w/w[ndx]
print(z.T)

[[0.10526316 0.52631579 1.        ]]


In [17]:
# 求解 Bw = z
w = np.linalg.solve(B,z)
print(w.T)

[[-0.37176274  0.45697577  0.86299081]]


In [18]:
# 取絕對值最大之特徵值
newW = max(abs(w))   # also w(k)/z(k)
print(newW)
ndx = list(w).index(newW)
#1/m = z[ndx]/w[ndx]
m = 1/newW
print('%8.4f'%(m))

[0.86299081]
  1.1588


In [19]:
# 步驟三
##將 w 尺度化
z = w/w[ndx]
print(z.T)
# 求解 Bw = z
w = np.linalg.solve(B,z)
print(w.T)

[[-0.43078412  0.52952565  1.        ]]
[[-0.47228753  0.48076953  0.96244564]]


In [20]:
# 取絕對值最大之特徵值
newW = max(abs(w))   # also w(k)/z(k)
print(newW)
ndx = list(w).index(newW)
#1/m = z[ndx]/w[ndx]
m = 1/newW
print('%8.4f'%(m))

[0.96244564]
  1.0390


In [21]:
# 所以 A 的特徵值中最靠近 15 的值，其近似值為：
final_m = 15 + m
print(final_m)

[16.03901972]
