In [4]:
from rayleigh import *
from power_B import *
import numpy as np

In [5]:
A = np.array([[21.0,7.0,-1.0],[5.0,7.0,7.0],[4.0,-4.0,20.0]])
w = np.array([[1.0],[1.0],[1.0]])
print(A)

[[21.  7. -1.]
 [ 5.  7.  7.]
 [ 4. -4. 20.]]


In [6]:
np.set_printoptions(precision=5)
[eigs,vecs] = power_B(A,w,10,0.001)
print('eigs: ',eigs)
print('vecs: ',end='')
for x in vecs.T:
    print(x,end='')
print()

iter       w1    r  z(x)
1 [27.] 5.866601196791445 [[1.     0.7037 0.7407]]
2 [25.1852] 2.323462560079786 [[1.     0.6    0.6353]]
3 [24.5647] 1.1430703517588843 [[1.     0.5556 0.5824]]
4 [24.3065] 0.6414628919369645 [[1.     0.5334 0.5523]]
5 [24.1816] 0.3891137638088378 [[1.     0.5211 0.534 ]]
6 [24.1135] 0.24652167270183445 [[1.     0.5136 0.5224]]
7 [24.0731] 0.15988784678320056 [[1.     0.5089 0.5148]]
8 [24.0478] 0.10500421463071548 [[1.     0.5059 0.5098]]
9 [24.0316] 0.06942299606672116 [[1.     0.5039 0.5065]]
10 [24.0209] 0.04606506250026031 [[1.     0.5026 0.5043]]
eigs:  [24.0209]
vecs: [1.     0.5026 0.5043]


In [7]:
np.set_printoptions(precision=5)
[eigs,vecs] = rayleigh(A,w,10,0.001)
print('eigs: ',eigs)
print('vecs: ',end='')
for x in vecs.T:
    print(x,end='')
print()

iter     m       r     z(x)
1     [22.] 3.559 [[0.5774 0.5774 0.5774]]
2     [23.3235] 1.822 [[0.6995 0.4922 0.5181]]
3     [23.725] 0.963 [[0.753  0.4518 0.4784]]
4     [23.867] 0.553 [[0.779  0.4328 0.4537]]
5     [23.9273] 0.339 [[0.7931 0.4231 0.4381]]
6     [23.9571] 0.216 [[0.8015 0.4176 0.428 ]]
7     [23.9735] 0.141 [[0.8067 0.4143 0.4214]]
8     [23.9831] 0.093 [[0.81   0.4123 0.417 ]]
9     [23.9891] 0.061 [[0.8122 0.4109 0.4141]]
10    [23.9928] 0.041 [[0.8137 0.41   0.4121]]
eigs:  [23.9928]
vecs: [0.8137 0.41   0.4121]


In [8]:
s = np.zeros(5)
print(s)

[0. 0. 0. 0. 0.]
