In [2]:
from numpy import *
for i in range(10):
    x = random.rand(4)-0.5
    print x

[ 0.24611461  0.2730003   0.3683448  -0.49640351]
[ 0.43604344  0.30808075  0.3288136   0.10252147]
[-0.29934622  0.06706441 -0.29705139  0.00089893]
[-0.18483886  0.27077208  0.24986139  0.24321681]
[-0.04340429 -0.27868482  0.16028141 -0.00039111]
[-0.46014571  0.27376889 -0.45248016  0.41175818]
[ 0.15696621 -0.02694983  0.32063686  0.37776272]
[-0.16286444  0.06116123 -0.32894443  0.06326165]
[ 0.0407553  -0.3488179   0.29294709  0.16467526]
[ 0.19075325  0.01284319 -0.28041944  0.23984591]
