In [1]:
import numpy as np

In [2]:
A = np.array([[6, 5, 0],[5, -1, 4],[5, 1, -14],[0, 4, 3]],dtype=float)

In [6]:
(r,c) = np.shape(A)
print(r,c)

4 3


In [8]:
tt = np.empty(c)
print(np.shape(tt))
print(tt)

(3,)
[9.34605037e-307 4.12452652e-027 6.01346953e-154]


In [9]:
for i in range(c):
    tt[i] = i
print(tt)

[0. 1. 2.]


In [10]:
t = np.empty(c)
t[0] = max(tt)
print(t)

[2. 1. 2.]


In [13]:
A = np.array([[5,4,1,1],[4,5,1,1],[1,1,4,2],[1,1,2,4]])
n = len(A)
for i in range(n-1):
   print(A[i+1:n,i])

[4 1 1]
[1 1]
[2]


In [12]:
print(A)

[[5 4 1 1]
 [4 5 1 1]
 [1 1 4 2]
 [1 1 2 4]]
