In [13]:
import numpy as np
def householder(A):
    (r,c) = np.shape(A)
    Q = np.identity(r)
    R= np.copy(A)
    for i in range(r - 1):
        x = R[i:,i]
        e = np.zeros_like(x)
        e[0] = np.linalg.norm(x)
        u = x - e
        v = u / np.linalg.norm(u)
        Q_i = np.identity(r)
        Q_i[i:,i:] -= 2.0 * np.outer(v,v)
        R = np.dot(Q_i,R)
        Q = np.dot(Q,Q_i)
    return (Q,R,c)
                
np.set_printoptions(precision=4, suppress=True)
A = np.array([[4,2/3,-4/3,4/3],[2/3,4,0,0],[-4/3,0,6,0],[4/3,0,2,6]])
b = np.array([[0],[0],[80],[0]])

(Q, R,c) = householder(A)
x=np.arange(c)
B = np.dot(Q.T,b)

x=np.linalg.solve(R,B)
print('Q:',Q)
print('R:',R)
print('x:',x.T)
#（made  cheng）
#--------------------- 
#作者：qq_34442920 
#来源：CSDN 
#原文：https://blog.csdn.net/qq_34442920/article/details/83244582 
#版权声明：本文为博主原创文章，转载请附上博文链接！

Q: [[ 0.8944 -0.1032  0.1423  0.4112]
 [ 0.1491  0.9862 -0.0237 -0.0685]
 [-0.2981  0.0917  0.8758  0.3684]
 [ 0.2981 -0.0917  0.4606 -0.831 ]]
R: [[ 4.4721  1.1926 -2.3851  2.9814]
 [-0.      3.8759  0.5045 -0.688 ]
 [ 0.      0.      5.9862  2.9535]
 [ 0.      0.      0.     -4.4376]]
x: [[ 7.4131 -1.2355 14.9807 -6.6409]]
