In [1]:
import numpy as np
import math

In [2]:
## ex-4.10
A = np.array([[11,-26,3,-12],[3,-12,3,-6],[31,-99,15,-44],[9,-10,-3,-4]],dtype=float)
np.set_printoptions(precision=4, suppress=True)
print(A)

[[ 11. -26.   3. -12.]
 [  3. -12.   3.  -6.]
 [ 31. -99.  15. -44.]
 [  9. -10.  -3.  -4.]]


In [8]:
def Hessenberg(A):
    (n, nn) = np.shape(A)
    for k in range(n-1):
        #x = np.zeros(n)
        w = np.zeros(n)
        C = np.zeros(shape=(n,nn))
        d = 0.0
        x = A[:,k]
        x = np.array([aa if i > k else 0 for i,aa in enumerate(x)])
        p = np.sign(x[k+1])
        if p == 0.0:
            p = 1
        g = np.linalg.norm(x)
        s = math.sqrt(2*g*(g+p*(x[k+1])))
        B = np.copy(A)
        if s != 0.0:
            w = x/s
            w[k+1] = (x[k+1]+p*g)/s
            w = w.reshape(-1,1)
            wt = w.reshape(1,-1)
            C = np.matmul(w,wt)
            d = np.matmul(np.matmul(wt,A),w)
            B = A - 2.0*np.dot(C,A) - 2.0 *np.dot(A,C) + 4.0 * d * C
        A = np.copy(B)
        print('k:',k+1)
        print('x = ',x.T)
        print('g = %8.4f'%g)
        print('s = %8.4f'%s)
        print('w = ',wt)
        print('d = ',d)
        print('C=',C)
        print('B=',B)
    return A
        

In [9]:
H = Hessenberg(A)
print(H)

k: 1
x =  [ 0.  3. 31.  9.]
g =  32.4191
s =  47.9220
w =  [[0.     0.7391 0.6469 0.1878]]
d =  [[-54.2491]]
C= [[0.     0.     0.     0.    ]
 [0.     0.5463 0.4781 0.1388]
 [0.     0.4781 0.4185 0.1215]
 [0.     0.1388 0.1215 0.0353]]
B= [[  11.        2.8687   28.2668   -4.6645]
 [ -32.4191   -8.078  -107.1151   16.6447]
 [   0.        0.0437    2.3056    0.1142]
 [   0.        2.8754  -20.5835    4.7724]]
k: 2
x =  [0.     0.     0.0437 2.8754]
g =   2.8757
s =   4.0977
w =  [[0.     0.     0.7125 0.7017]]
d =  [[-6.7132]]
C= [[0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.5076 0.4999]
 [0.     0.     0.4999 0.4924]]
B= [[ 11.       2.8687   4.2341 -28.3345]
 [-32.4191  -8.078  -15.0141 107.3558]
 [  0.      -2.8757   4.4607 -20.6163]
 [  0.      -0.       0.0814   2.6174]]
k: 3
x =  [0.     0.     0.     0.0814]
g =   0.0814
s =   0.1628
w =  [[0. 0. 0. 1.]]
d =  [[2.6174]]
C= [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]]
B= [[  11.  

In [10]:
B = np.array([[15,-2,-2,-1],[10,6,-4,-2],[10,4,-1,-3],[10,4,-2,-2]])
#H1 = ALG.hessenberg(B)
H1 = Hessenberg(B)
print("+++++++++++++++++++++++++++++++++++")
print(H1)

k: 1
x =  [ 0 10 10 10]
g =  17.3205
s =  30.7638
w =  [[0.     0.8881 0.3251 0.3251]]
d =  [[4.4641]]
C= [[0.     0.     0.     0.    ]
 [0.     0.7887 0.2887 0.2887]
 [0.     0.2887 0.1057 0.1057]
 [0.     0.2887 0.1057 0.1057]]
B= [[ 15.       2.8868  -0.2113   0.7887]
 [-17.3205   0.       7.       7.    ]
 [  0.       0.       2.366   -0.366 ]
 [  0.      -0.       1.366    0.634 ]]
k: 2
x =  [ 0.  0.  0. -0.]
g =   0.0000
s =   0.0000
w =  [[ 0.      0.      0.7071 -0.7071]]
d =  [[1.]]
C= [[ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.5 -0.5]
 [ 0.   0.  -0.5  0.5]]
B= [[ 15.       2.8868   0.7887  -0.2113]
 [-17.3205   0.       7.       7.    ]
 [  0.      -0.       0.634    1.366 ]
 [  0.      -0.      -0.366    2.366 ]]
k: 3
x =  [ 0.     0.     0.    -0.366]
g =   0.3660
s =   0.7321
w =  [[ 0.  0.  0. -1.]]
d =  [[2.366]]
C= [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]]
B= [[ 15.       2.8868   0.7887   0.2113]
 [-17.3205   0.       7.      -7. 