In [48]:
import numpy as np

In [71]:
n = 4
x = np.ones(n)
k = 2
print(x)
x = [aa if i > k else 0 for i,aa in enumerate(x)]
print(x)

[1. 1. 1. 1.]
[0, 0, 0, 1.0]


In [50]:
A = np.array([[5,14,1,1],[4,5,1,1],[1,1,4,2],[1,1,2,4]],dtype=float)
print(A)


[[ 5. 14.  1.  1.]
 [ 4.  5.  1.  1.]
 [ 1.  1.  4.  2.]
 [ 1.  1.  2.  4.]]


In [51]:
g = A[:,k]
print(g)

[14.  5.  1.  1.]


In [53]:
wt =  np.array([0., 0.7391, 0.6469, 0.1878]).reshape(4,1)
w = wt.reshape(1,-1)
print(wt.shape, w.shape)
H = np.matmul(wt,w)
print(H.shape)
print(H)

(4, 1) (1, 4)
(4, 4)
[[0.         0.         0.         0.        ]
 [0.         0.54626881 0.47812379 0.13880298]
 [0.         0.47812379 0.41847961 0.12148782]
 [0.         0.13880298 0.12148782 0.03526884]]
