In [1]:
import numpy as np
from jacobi import *

In [2]:
A = np.array([[8,1,-1],[2,1,9],[1,-7,2]])
b = np.array([[8],[12],[-4]])

In [3]:
sol,p = jacobi(A)
print(sol)
print(p)

[ 8 -8 10]
[[ 0.99033427 -0.10335016 -0.09250282]
 [ 0.13870121  0.73792581  0.66047518]
 [ 0.         -0.66692146  0.74512802]]


In [25]:
# step 1 尺度化
A = np.array([[8,1,-1],[2,1,9],[1,-7,2]])
b = np.array([[8],[12],[-4]])
r,c = A.shape
print(r,c)
B = np.zeros((r,c+1),dtype=float)
for i in range(r):
    for j in range(c):
        B[i][j]=A[i][j]
    B[i][j+1] = b[i]
print(B)

3 3
[[ 8.  1. -1.  8.]
 [ 2.  1.  9. 12.]
 [ 1. -7.  2. -4.]]


In [26]:
r1,c1 = B.shape
H = B.copy()
print(H)
for i in range(r1):
    s = B[i][i]
    for j in range(c1):
        H[i][j] = B[i][j]/s
print(H)
    

[[ 8.  1. -1.  8.]
 [ 2.  1.  9. 12.]
 [ 1. -7.  2. -4.]]
[[ 1.     0.125 -0.125  1.   ]
 [ 2.     1.     9.    12.   ]
 [ 0.5   -3.5    1.    -2.   ]]
