In [1]:
import numpy as np
from jacobi import *

In [2]:
A = np.array([[8,1,-1],[2,1,9],[1,-7,2]])
b = np.array([[8],[12],[-4]])

In [3]:
sol,p = jacobi(A)
print(sol)
print(p)

[ 8 -8 10]
[[ 0.99033427 -0.10335016 -0.09250282]
 [ 0.13870121  0.73792581  0.66047518]
 [ 0.         -0.66692146  0.74512802]]


In [25]:
# step 1 尺度化
A = np.array([[8,1,-1],[2,1,9],[1,-7,2]])
b = np.array([[8],[12],[-4]])
r,c = A.shape
print(r,c)
B = np.zeros((r,c+1),dtype=float)
for i in range(r):
    for j in range(c):
        B[i][j]=A[i][j]
    B[i][j+1] = b[i]
print(B)

3 3
[[ 8.  1. -1.  8.]
 [ 2.  1.  9. 12.]
 [ 1. -7.  2. -4.]]


In [26]:
r1,c1 = B.shape
H = B.copy()
print(H)
for i in range(r1):
    s = B[i][i]
    for j in range(c1):
        H[i][j] = B[i][j]/s
print(H)
    

[[ 8.  1. -1.  8.]
 [ 2.  1.  9. 12.]
 [ 1. -7.  2. -4.]]
[[ 1.     0.125 -0.125  1.   ]
 [ 2.     1.     9.    12.   ]
 [ 0.5   -3.5    1.    -2.   ]]


In [15]:
import numpy as np

A = np.array([[8,1,-1],[2,1,9],[1,-7,2]])
b = np.array([[8],[12],[-4]])
maxit = 10
tol = 0.001
r,c = A.shape
x = np.array([0,0,0])
nx = np.array([0,0,0])
def f_1(x,a,b):
    return (1/a[0])*(b-a[1]*x[1]-a[2]*x[2])

def f_2(x,a,b):
    return (1/a[1])*(b-a[0]*x[0]-a[2]*x[2])

def f_3(x,a,b):
    return (1/a[2])*(b-a[0]*x[0]-a[1]*x[1])

for i in range(maxit):
    nx[0] = f_1(x,A[0],b[0])
    nx[1] = f_2(x,A[1],b[1])
    nx[2] = f_3(x,A[2],b[2])
    r = (np.linalg.norm(nx)-np.linalg.norm(x))/np.linalg.norm(nx)
    print(i+1,nx,r)
    x = nx

1 [ 1 12 -2] 1.0
2 [  0  30 103] 0.0
3 [   10  -935 -3279] 0.0
4 [  -292  30107 105518] 0.0
5 [    9427  -968504 -3394479] 0.0
6 [  -303245  31156813 109200466] 0.0
7 [    9755457 -1002315096   781986729] 0.0
8 [ 223037729 1105978585 -535561115] 0.0
9 [-205192461  935467673 -918234212] 0.0
10 [-231712734  137598796  597452151] 0.0


C:\Users\jumbo\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: RuntimeWarning: overflow encountered in long_scalars
C:\Users\jumbo\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: RuntimeWarning: overflow encountered in long_scalars
  


In [9]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)
A = np.array([[8,1,-1],[2,1,9],[1,-7,2]])
b = np.array([[8],[12],[-4]])
maxit = 10
tol = 0.001
r,c = A.shape
x = np.array([0,0,0])
nx = np.array([0,0,0])
B = np.zeros((r,c),dtype=float)
bb = np.zeros(c,dtype=float)
for i in range(r):
    s = A[i][i]
    B[i] = A[i]/s
    bb[i] = b[i]/s
print(B)
print(bb)

[[ 1.     0.125 -0.125]
 [ 2.     1.     9.   ]
 [ 0.5   -3.5    1.   ]]
[ 1. 12. -2.]


In [18]:
def cross(a,b):
    sumx = 0.0
    for i in range(len(a)):
        sumx += a[i]*b[i]
    return sumx

def disp(x):
    for i in range(len(x)):
       print('%8.4f'%x[i],', ',end='')
    
r,c = B.shape
x = np.zeros(c,dtype=float)
nx = np.zeros(c)
np.set_printoptions(precision=4, suppress=True)
print('index    x1          x2     x3          r')
for k in range(maxit):
    for ii in range(c):
        nx[ii] = bb[ii] - cross(B[ii],x)  
    r = (np.linalg.norm(nx)-np.linalg.norm(x))/np.linalg.norm(nx)
    x = nx
    print(k+1,end='   ')
    disp(x)
    print(' ','%8.4f'%r)

index    x1          x2     x3          r
1     1.0000 ,  12.0000 ,  -2.0000 ,     1.0000
2    -1.7500 ,  21.5000 ,  76.1250 ,     0.0000
3     9.5781 , -713.7812 , -2581.1484 ,     0.0000
4   -241.9990 , 24440.1152 , 88240.5513 ,     0.0000
5   8218.0535 , -835029.1837 , -3014953.7210 ,     0.0000
6   -280707.6207 , 28531039.9145 , 103013945.2320 ,     0.0000
7   9591071.7854 , -974838678.5729 , -3519744858.1298 ,     0.0000
8   -327704343.2300 , 33307951100.2015 , 120261425878.4502 ,     0.0000
9   11196888691.5111 , -1138054561377.2751 , -4109050835046.6685 ,     0.0000
10   -382571422899.1852 , 38884654922607.6641 , 140396628775621.0938 ,     0.0000
