In [1]:
import numpy as np
from jacobi import *

In [2]:
A = np.array([[8,1,-1],[2,1,9],[1,-7,2]])
b = np.array([[8],[12],[-4]])

In [3]:
sol,p = jacobi(A)
print(sol)
print(p)

[ 8 -8 10]
[[ 0.99033427 -0.10335016 -0.09250282]
 [ 0.13870121  0.73792581  0.66047518]
 [ 0.         -0.66692146  0.74512802]]


In [25]:
# step 1 尺度化
A = np.array([[8,1,-1],[2,1,9],[1,-7,2]])
b = np.array([[8],[12],[-4]])
r,c = A.shape
print(r,c)
B = np.zeros((r,c+1),dtype=float)
for i in range(r):
    for j in range(c):
        B[i][j]=A[i][j]
    B[i][j+1] = b[i]
print(B)

3 3
[[ 8.  1. -1.  8.]
 [ 2.  1.  9. 12.]
 [ 1. -7.  2. -4.]]


In [26]:
r1,c1 = B.shape
H = B.copy()
print(H)
for i in range(r1):
    s = B[i][i]
    for j in range(c1):
        H[i][j] = B[i][j]/s
print(H)
    

[[ 8.  1. -1.  8.]
 [ 2.  1.  9. 12.]
 [ 1. -7.  2. -4.]]
[[ 1.     0.125 -0.125  1.   ]
 [ 2.     1.     9.    12.   ]
 [ 0.5   -3.5    1.    -2.   ]]


In [15]:
import numpy as np

A = np.array([[8,1,-1],[2,1,9],[1,-7,2]])
b = np.array([[8],[12],[-4]])
maxit = 10
tol = 0.001
r,c = A.shape
x = np.array([0,0,0])
nx = np.array([0,0,0])
def f_1(x,a,b):
    return (1/a[0])*(b-a[1]*x[1]-a[2]*x[2])

def f_2(x,a,b):
    return (1/a[1])*(b-a[0]*x[0]-a[2]*x[2])

def f_3(x,a,b):
    return (1/a[2])*(b-a[0]*x[0]-a[1]*x[1])

for i in range(maxit):
    nx[0] = f_1(x,A[0],b[0])
    nx[1] = f_2(x,A[1],b[1])
    nx[2] = f_3(x,A[2],b[2])
    r = (np.linalg.norm(nx)-np.linalg.norm(x))/np.linalg.norm(nx)
    print(i+1,nx,r)
    x = nx

1 [ 1 12 -2] 1.0
2 [  0  30 103] 0.0
3 [   10  -935 -3279] 0.0
4 [  -292  30107 105518] 0.0
5 [    9427  -968504 -3394479] 0.0
6 [  -303245  31156813 109200466] 0.0
7 [    9755457 -1002315096   781986729] 0.0
8 [ 223037729 1105978585 -535561115] 0.0
9 [-205192461  935467673 -918234212] 0.0
10 [-231712734  137598796  597452151] 0.0


C:\Users\jumbo\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: RuntimeWarning: overflow encountered in long_scalars
C:\Users\jumbo\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: RuntimeWarning: overflow encountered in long_scalars
  


In [1]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)
A = np.array([[8,1,-1],[2,1,9],[1,-7,2]])
b = np.array([[8],[12],[-4]])
maxit = 10
tol = 0.001
r,c = A.shape
x = np.array([0,0,0])
nx = np.array([0,0,0])
B = np.zeros((r,c),dtype=float)
bb = np.zeros(c,dtype=float)
for i in range(r):
    s = A[i][i]
    B[i] = A[i]/s
    bb[i] = b[i]/s
print(B)
print(bb)

[[ 1.     0.125 -0.125]
 [ 2.     1.     9.   ]
 [ 0.5   -3.5    1.   ]]
[ 1. 12. -2.]


In [6]:
r,c = B.shape
x = np.zeros(c,dtype=float)
nx = np.zeros(c)

for k in range(maxit):
    for ii in range(r):
        sumx = 0.0
        for j in range(c):
            if j != ii:
                sumx += B[ii][j]*x[ii]
        nx[ii] = bb[ii] - sumx
    n1 = np.linalg.norm(nx)
    n2 = np.linalg.norm(x)
    r = (n1-n2)/n1
    print(k+1,nx,r)
    if r < tol:
        break
    x = nx
        

1 [ 1. 12. -2.] 1.0


TypeError: 'numpy.float64' object cannot be interpreted as an integer

In [10]:
r,c = B.shape
x = np.zeros(c,dtype=float)
nx = np.zeros(c)

for k in range(maxit):
    for ii in range(r):
        #sumx = 0.0
        sumx += B[ii]*x[ii].T
        nx[ii] = bb[ii] - sumx
    n1 = np.linalg.norm(nx)
    n2 = np.linalg.norm(x)
    r = (n1-n2)/n1
    print(k+1,nx,r)
    if r < tol:
        break
    x = nx

ValueError: setting an array element with a sequence.