In [2]:
import numpy as np

A = np.array([[8,1,-1],[2,1,9],[1,-7,2]])
b = np.array([[8],[12],[-4]])
r,c = A.shape
for i in range(r):
    print(A[i],b[i])

[ 8  1 -1] [8]
[2 1 9] [12]
[ 1 -7  2] [-4]


In [3]:
r,c = A.shape
for i in range(c):
    x = A[i] * b.T
    print(x)
    print("***********")

[[64 12  4]]
***********
[[ 16  12 -36]]
***********
[[  8 -84  -8]]
***********


In [2]:
import numpy as np
x = np.zeros(3,dtype=float)
b = np.array([-1,6,-3])
c = x-b
for i in range(len(x)):
    print('%8.4f'%c[i],end=', ')
print('%8.4f'%np.linalg.norm(c))

  1.0000,  -6.0000,   3.0000,   6.7823
